name: Fabricefardeau
favicon: null
layout_spectrum: 0.9734035783912987
typography_spectrum: 0.3259566642809659
title: Fabrice Fardeau
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.01997281424701214
  lightness: 0.9413686008192599
  saturation: 0.7348187221214175
  rhythmicContrast: 0.01859171479009092
purpose: []
