title: Fabrice Fardeau
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7348187221214175
  brandStrength: 0.2336197
  lightness: 0.5625
  brandColors:
    - '#FFFFFF'
    - '#0F0F17'
    - '#3D4248'
    - '#C1914F'
    - '#C8BEC7'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Fabricefardeau
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.40808
layout_spectrum: 0.9210526
